//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITSupport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attachment
    {
        public int AttachmentId { get; set; }
        public int CaseId { get; set; }
        public string FileName { get; set; }
        public string FilePath { get; set; }
        public Nullable<long> FileSize { get; set; }
        public string ContentType { get; set; }
        public int UploadedByUserId { get; set; }
        public System.DateTime UploadedAt { get; set; }
    
        public virtual Case Case { get; set; }
        public virtual User User { get; set; }
    }
}
