//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITSupport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Case
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Case()
        {
            this.Attachments = new HashSet<Attachment>();
            this.CaseHistories = new HashSet<CaseHistory>();
            this.CaseNotes = new HashSet<CaseNote>();
        }
    
        public int CaseId { get; set; }
        public string CaseNumber { get; set; }
        public int StatusId { get; set; }
        public int PriorityId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public int ContactId { get; set; }
        public int ProgramId { get; set; }
        public string Country { get; set; }
        public Nullable<int> OwnerId { get; set; }
        public int CreatedByUserId { get; set; }
        public string PreferredContact { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public Nullable<System.DateTime> ClosedAt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attachment> Attachments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CaseHistory> CaseHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CaseNote> CaseNotes { get; set; }
        public virtual Contact Contact { get; set; }
        public virtual User User { get; set; }
        public virtual SupportEngineer SupportEngineer { get; set; }
        public virtual Priority Priority { get; set; }
        public virtual Program Program { get; set; }
        public virtual CaseStatus CaseStatus { get; set; }
    }
}
