//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITSupport.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaseHistory
    {
        public int HistoryId { get; set; }
        public int CaseId { get; set; }
        public int ChangedByUserId { get; set; }
        public string FieldChanged { get; set; }
        public string OldValue { get; set; }
        public string NewValue { get; set; }
        public System.DateTime ChangedAt { get; set; }
    
        public virtual Case Case { get; set; }
        public virtual User User { get; set; }
    }
}
